### ISSUE TITLE
MIT 6.824 schedule 讨论

### ISSUE THREAD

**Issue by fishfish327** [fishfish327/MIT6.824-public-discuss#1]
大家好, 利用这个issue 和大家一起讨论一下 mit6.824的学习计划

我个人的计划现在是follow 2020的版本
下面是我关于lab的计划: 
- [ ] week 1  go prep, lab 1
- [ ] week 2  lab 1
- [ ] week 3 lab2 A
- [ ] week 4 lab2 B
- [ ] week 5 lab2 C
- [ ] week 6 lab3 A
- [ ] week 7 lab3 B
- [ ] week 8~ 9  lab4 A
- [ ] week 10~11 lab4 B

欢迎大家评论自己的想法和计划，互相交流

**Comment by lchen22643** [comment]
楼主我是那个准备趁着放假肝肝到哪算哪的小伙伴 评论表支持 有啥问题就直接在这问了？

**Comment by ErEvEc** [comment]
同放假肝，开学的课可能忙死

**Comment by fishfish327** [comment]
> 楼主我是那个准备趁着放假肝肝到哪算哪的小伙伴 评论表支持 有啥问题就直接在这问了？

好啊好啊，我知道你是谁了哈哈哈哈
